apiVersion: v1
kind: Service
metadata:
  name: SampleService
  labels: 
    app: SampleService
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: SampleService
    tier: SampleService
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: SampleService
  labels:
    app: SampleService
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: SampleService
        tier: SampleService
    spec:
      containers:
      - image: sibendudas/gs-spring-boot-docker
        name: SampleService
        ports:
        - containerPort: 8080
          name: SampleService
