apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels: 
    app: sample-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sample-service
    tier: sample-service
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-service
  labels:
    app: sample-service
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sample-service
        tier: sample-service
    spec:
      containers:
      - image: sibendudas/gs-spring-boot-docker
        name: sample-service
        ports:
        - containerPort: 8080
          name: sample-service
